zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181:2181"
kafka:
  build: .
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
    KAFKA_CREATE_TOPICS: "ex1:1:1,starwars:1:1,ex3:2:1,test:1:1"
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
